TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
SHORT_CODE_LENGTH = 6

MIN_AMOUNT = 1
MIN_COOKING_TIME = 1
MAX_POSITIVE_SMALLINT = 32767
